### ISSUE TITLE
"pau" is ignored in a label

### ISSUE THREAD

**Issue by korguchi** [sarulab-speech/jsut-label#1]
I found an example that "pau" is ignored in the contexts before and after it.
In BASIC5000_1975.lab,
> 20500000 21700000 e^n-i+gy=a ...
> 21700000 22100000 n^i-pau+gy=a ...
> 22100000 22799999 n^i-gy+a=k/ ...

This is supposed to be as follows:
> 20500000 21700000 e^n-i+pau=gy ...
> 21700000 22100000 n^i-pau+gy=a ...
> 22100000 22799999 i^pau-gy+a=k/ ...

You might find more examples like this if you look for them.
Thanks.

**Comment by hyama5** [comment]
Thanks for your report. I'll check it for all labels.

**Comment by hyama5** [comment]
I found almost all labels were wrong and fixed the errors.
Could you check whether the following modifications are correct?
https://github.com/sarulab-speech/jsut-label/commit/4f862e705acd35e39f5b754cc7c9857f8aa2286a

**Comment by korguchi** [comment]
Sorry for replying so late.
I confirmed they are correct.
Thanks.
